
package com.suitepagos.backend.soap.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "APILegalCustomerOutAppSvc", targetNamespace = "http://xmlns.banesco.com/ApplicationService/APILegalCustomerOutAppSvc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactoryLegal.class
})
public interface APILegalCustomerOutAppSvc {


    /**
     * 
     * @param readCustomerData
     * @return
     *     returns com.suitepagos.backend.soap.webservice.ReadCustomerDataRs
     */
    @WebMethod(action = "readCustomerData")
    @WebResult(name = "readCustomerData_Rs", targetNamespace = "http://xmlns.banesco.com/ApplicationService/APILegalCustomerOutAppSvc", partName = "readCustomerData")
    public ReadCustomerDataRsLegal readCustomerData(
        @WebParam(name = "readCustomerData_Rq", targetNamespace = "http://xmlns.banesco.com/ApplicationService/APILegalCustomerOutAppSvc", partName = "readCustomerData")
        ReadCustomerDataRqLegal readCustomerData);

}
