
package com.suitepagos.backend.soap.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "APINaturalCustomerOutAppSvc", targetNamespace = "http://xmlns.banesco.com/ApplicationService/APINaturalCustomerOutAppSvc", wsdlLocation = "http://10.135.5.29:8001/APINaturalCustomerOutAppSvc/proxy/APINaturalCustomerOutAppSvc?wsdl")
public class APINaturalCustomerOutAppSvc_Service
    extends Service
{

    private final static URL APINATURALCUSTOMEROUTAPPSVC_WSDL_LOCATION;
    private final static WebServiceException APINATURALCUSTOMEROUTAPPSVC_EXCEPTION;
    private final static QName APINATURALCUSTOMEROUTAPPSVC_QNAME = new QName("http://xmlns.banesco.com/ApplicationService/APINaturalCustomerOutAppSvc", "APINaturalCustomerOutAppSvc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.135.5.29:8001/APINaturalCustomerOutAppSvc/proxy/APINaturalCustomerOutAppSvc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APINATURALCUSTOMEROUTAPPSVC_WSDL_LOCATION = url;
        APINATURALCUSTOMEROUTAPPSVC_EXCEPTION = e;
    }

    public APINaturalCustomerOutAppSvc_Service() {
        super(__getWsdlLocation(), APINATURALCUSTOMEROUTAPPSVC_QNAME);
    }

    public APINaturalCustomerOutAppSvc_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), APINATURALCUSTOMEROUTAPPSVC_QNAME, features);
    }

    public APINaturalCustomerOutAppSvc_Service(URL wsdlLocation) {
        super(wsdlLocation, APINATURALCUSTOMEROUTAPPSVC_QNAME);
    }

    public APINaturalCustomerOutAppSvc_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APINATURALCUSTOMEROUTAPPSVC_QNAME, features);
    }

    public APINaturalCustomerOutAppSvc_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public APINaturalCustomerOutAppSvc_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns APINaturalCustomerOutAppSvc
     */
    @WebEndpoint(name = "APINaturalCustomerOutAppSvcSOAP")
    public APINaturalCustomerOutAppSvc getAPINaturalCustomerOutAppSvcSOAP() {
        return super.getPort(new QName("http://xmlns.banesco.com/ApplicationService/APINaturalCustomerOutAppSvc", "APINaturalCustomerOutAppSvcSOAP"), APINaturalCustomerOutAppSvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APINaturalCustomerOutAppSvc
     */
    @WebEndpoint(name = "APINaturalCustomerOutAppSvcSOAP")
    public APINaturalCustomerOutAppSvc getAPINaturalCustomerOutAppSvcSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.banesco.com/ApplicationService/APINaturalCustomerOutAppSvc", "APINaturalCustomerOutAppSvcSOAP"), APINaturalCustomerOutAppSvc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APINATURALCUSTOMEROUTAPPSVC_EXCEPTION!= null) {
            throw APINATURALCUSTOMEROUTAPPSVC_EXCEPTION;
        }
        return APINATURALCUSTOMEROUTAPPSVC_WSDL_LOCATION;
    }

}
